# Generated by Django 5.2.8 on 2025-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag_type',
            field=models.CharField(choices=[('course', 'Course'), ('interest', 'Interest'), ('hidden', 'Hidden')], default='course', max_length=10),
        ),
    ]
