# Generated by Django 5.2.7 on 2025-10-23 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_skippedmatch_options_like_delete_buddyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='skippedmatch',
            name='action_type',
            field=models.CharField(choices=[('skip', 'Skip'), ('like', 'Like')], default='skip', max_length=4),
        ),
        migrations.AlterField(
            model_name='skippedmatch',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skippedmatch',
            name='skipped_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_actioned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
