# Generated by Django 5.2.8 on 2025-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skippedmatch_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_age_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='profile',
            name='match_age_min',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
