# Generated by Django 5.2.7 on 2025-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skippedmatch_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skippedmatch',
            name='action_type',
            field=models.CharField(choices=[('skip', 'Skip'), ('like', 'Like'), ('remove', 'Remove')], default='skip', max_length=6),
        ),
    ]
