# Generated by Django 5.2.8 on 2025-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
